//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int bookingid { get; set; }
        public int cid { get; set; }
        public string carno { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime enddate { get; set; }
        public int rentalamount { get; set; }
        public Nullable<System.DateTime> actualenddate { get; set; }
        public Nullable<int> penaltyamount { get; set; }
        public string status { get; set; }
        public Nullable<int> did { get; set; }
        public string address { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
    }
}
