//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class carrentalEntities : DbContext
    {
        public carrentalEntities()
            : base("name=carrentalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<owner> owners { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<chauffer> chauffers { get; set; }
        public virtual DbSet<offer> offers { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<offerused> offeruseds { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<carrequest> carrequests { get; set; }
        public virtual DbSet<vehicle> vehicles { get; set; }
        public virtual DbSet<carstatu> carstatus { get; set; }
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<cardata> cardatas { get; set; }
    }
}
