//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cardetail
    {
        public string carno { get; set; }
        public string color { get; set; }
        public string model { get; set; }
        public string brand { get; set; }
        public Nullable<int> seatingcapacity { get; set; }
        public Nullable<double> mileage { get; set; }
        public string preferance { get; set; }
        public string carimage { get; set; }
    }
}
