//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public string carno { get; set; }
        public int cid { get; set; }
        public string rating { get; set; }
        public string description { get; set; }
        public int fid { get; set; }
    }
}
