//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class offer
    {
        public int offerid { get; set; }
        public string promocode { get; set; }
        public string description { get; set; }
        public Nullable<int> isonetime { get; set; }
        public string ofbased { get; set; }
        public Nullable<int> discountpercent { get; set; }
        public Nullable<int> discountamount { get; set; }
    }
}
