//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int transactionid { get; set; }
        public int bookingid { get; set; }
        public int amountpaid { get; set; }
        public string paymentmode { get; set; }
        public string cardno { get; set; }
        public string nameoncard { get; set; }
        public string phone { get; set; }
        public System.DateTime date { get; set; }
    }
}
