//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class rentcar
    {
        public string carno { get; set; }
        public System.DateTime startrent { get; set; }
        public System.DateTime endrent { get; set; }
        public int rentgiven { get; set; }
    }
}
