//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehicle()
        {
            this.cardatas = new HashSet<cardata>();
        }
    
        public int vehicleid { get; set; }
        public string color { get; set; }
        public string model { get; set; }
        public string brand { get; set; }
        public int capacity { get; set; }
        public double mileage { get; set; }
        public Nullable<int> quantity { get; set; }
        public int priceperday { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cardata> cardatas { get; set; }
    }
}
